export const STRINGS = {
  api: {
    networkError: "Serveur inaccessible. Vérifiez votre connexion.",
    invalidCredentials: "Identifiants incorrects.",
    registerError: "Erreur lors de la création du compte.",
    sessionExpired: "Session expirée.",
    unauthorized: "Non autorisé.",
    unauthenticated: "Non authentifié",
    profileLoadError: "Impossible de charger le profil.",
    incidentsLoadError: "Impossible de charger les signalements.",
    unknownError: "Erreur inconnue",
    genericError: "Une erreur est survenue.",
  },
  toast: {
    missingFieldsTitle: "Champs manquants",
    missingFields: "Veuillez remplir tous les champs.",
    passwordMismatchTitle: "Mots de passe différents",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    loginFailedTitle: "Connexion échouée",
    registerFailedTitle: "Inscription échouée",
    registerSuccessTitle: "Compte créé !",
    registerSuccess: "Vous pouvez maintenant vous connecter.",
    reportSuccessTitle: "Signalement envoyé",
    reportSuccess: "Votre incident a été enregistré.",
  },
  alert: {
    errorTitle: "Erreur",
    sessionExpiredTitle: "Session expirée",
    sessionExpiredMsg: "Reconnectez-vous pour continuer.",
    deleteIncidentTitle: "Supprimer l'incident",
    deleteIncidentMsg: "Cette action est irréversible. Confirmer la suppression ?",
  },
  emptyState: {
    noMyIncidents: "Aucun signalement pour le moment.",
    noFilterResults: "Aucun résultat pour ces filtres.",
    noAllIncidents: "Aucun signalement dans la ville.",
    agentAllDone: "Tout est traité, bravo !",
    noIncidents: "Aucun signalement.",
  },
} as const;
