export const STRINGS = {
  api: {
    networkError: "Connexion impossible. Vérifiez votre réseau et réessayez.",
    invalidCredentials: "Identifiant ou mot de passe incorrect.",
    registerError: "La création de compte a échoué. Réessayez dans un moment.",
    sessionExpired: "Votre session a expiré, veuillez vous reconnecter.",
    unauthorized: "Vous n'avez pas accès à cette fonctionnalité.",
    unauthenticated: "Veuillez vous connecter pour continuer.",
    profileLoadError: "Impossible de charger vos informations. Réessayez.",
    incidentsLoadError: "Impossible de charger les signalements. Réessayez.",
    unknownError: "Une erreur inattendue s'est produite.",
    genericError: "Quelque chose s'est mal passé. Réessayez.",
  },
  toast: {
    missingFieldsTitle: "Champs manquants",
    missingFields: "Veuillez remplir tous les champs avant de continuer.",
    passwordMismatchTitle: "Mots de passe différents",
    passwordMismatch: "Les deux mots de passe ne correspondent pas.",
    loginFailedTitle: "Connexion échouée",
    registerFailedTitle: "Inscription échouée",
    registerSuccessTitle: "Compte créé !",
    registerSuccess: "Bienvenue ! Vous pouvez maintenant vous connecter.",
    reportSuccessTitle: "Signalement envoyé !",
    reportSuccess: "Merci, votre signalement a bien été enregistré.",
  },
  photos: {
    permissionDeniedCamera: "Autorisez l'accès à l'appareil photo dans les paramètres.",
    permissionDeniedGallery: "Autorisez l'accès à vos photos dans les paramètres.",
    limitReached: "Vous avez atteint la limite de 3 photos par signalement.",
    uploadError: "Certaines photos n'ont pas pu être envoyées.",
    deleteError: "Impossible de supprimer la photo. Réessayez.",
    loadError: "Impossible de charger les photos.",
    deleteConfirmTitle: "Supprimer la photo",
    deleteConfirmMsg: "Cette suppression est définitive. Confirmer ?",
  },
  alert: {
    errorTitle: "Oups, une erreur",
    sessionExpiredTitle: "Session expirée",
    sessionExpiredMsg: "Votre session a expiré. Reconnectez-vous pour continuer.",
    deleteIncidentTitle: "Supprimer le signalement",
    deleteIncidentMsg: "Cette suppression est définitive. Confirmer ?",
  },
  emptyState: {
    noMyIncidents: "Vous n'avez pas encore fait de signalement.",
    noFilterResults: "Aucun résultat pour ces filtres.",
    noAllIncidents: "Aucun signalement dans la ville pour le moment.",
    agentAllDone: "Tout est traité, bon travail !",
    noIncidents: "Aucun signalement.",
  },
} as const;
